version: '3'
services:
  php_7-2_apache:
    build:
      context: ./docker_config/php_7-2_apache
      dockerfile: Dockerfile
    container_name: php_7-2_apache
    restart: on-failure
    depends_on:
      - mysql_8
    volumes:
      - ./app/:/var/www/html/
    ports:
      - 80:80
  mysql_8:
    container_name: mysql_8
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "g0K3?9P3"
      MYSQL_DATABASE: Main
      MYSQL_USER: developer
      MYSQL_PASSWORD: "l%4fU39f"
    volumes:
      - ./db_dumps/:/docker-entrypoint-initdb.d/
    expose:
      - 3306